### ISSUE TITLE
Friend requests using askless (and not http)

### ISSUE THREAD

**Issue by rn-netizen** [RodrigoBertotti/Askless#3]
Hi Rodrigo,

I was wondering how we could create a friend request system using askless. It's not hard to create it using http but i wonder how we would do it using askless. I tried using server actions but i don't really see how we can do it.

**Comment by RodrigoBertotti** [comment]
Hello, thank you for checking Askless

Please check the documentation and examples, the information you need is there  🤗

- Askless Server Side:
   - Documentation: https://github.com/RodrigoBertotti/Askless/blob/dev/documentation.md
   - Examples: https://github.com/RodrigoBertotti/Askless/tree/dev/example
- Askless Flutter Side: 
   - Documentation: https://github.com/RodrigoBertotti/askless-flutter-client/blob/dev/documentation.md
   - Examples: https://github.com/RodrigoBertotti/askless-flutter-client/tree/dev/example

I wish you success in your project!

**Comment by rn-netizen** [comment]
Thank you for your response, it helped me so much! Also, is there something
to test requests to the server like postman? I tried postman but it doesn't
work with askless and also, when i try to use js client I get errors.

**Comment by RodrigoBertotti** [comment]
I'm glad it helped! 

Unfortunately, there isn't a tool for testing Askless, Postman doesn't work because Askless relies on WebSocket rather than HTTP

**Comment by RodrigoBertotti** [comment]
Also, keep in mind the JS Client for Askless is discontinued, Askless is a Node.js Framework that only supports Flutter clients right now
