### ISSUE TITLE
Getting this error warning: respondWithError: the client "(no ID)" could not perform the operation on (READ)askless-internal/call/receive, result is PENDING_AUTHENTICATION, authentication is "pending", did you handle the onUnauthenticatedListener on the App side? (initAndConnect)

### ISSUE THREAD

**Issue by aakash-a-dev** [RodrigoBertotti/Askless#6]
Hi can you help me understand why this coming on my backend this issue
warning: respondWithError: the client "(no ID)" could not perform the operation on (READ)askless-internal/call/receive, result is PENDING_AUTHENTICATION, authentication is "pending", did you handle the onUnauthenticatedListener on the App side? (initAndConnect)

**Comment by RodrigoBertotti** [comment]
An update has just been released to fix this problem, thank you for checking my project!
